In [1]:
%pip install pandas
%pip install sleeper-py

Requirement already satisfied: pandas in /Users/scottenriquez/opt/anaconda3/lib/python3.9/site-packages (1.3.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/scottenriquez/opt/anaconda3/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /Users/scottenriquez/opt/anaconda3/lib/python3.9/site-packages (from pandas) (2021.3)
Requirement already satisfied: numpy>=1.17.3 in /Users/scottenriquez/opt/anaconda3/lib/python3.9/site-packages (from pandas) (1.20.3)
Requirement already satisfied: six>=1.5 in /Users/scottenriquez/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: sleeper-py in /Users/scottenriquez/opt/anaconda3/lib/python3.9/site-packages (1.0.1)
Requirement already satisfied: requests>=2.28.1 in /Users/scottenriquez/opt/anaconda3/lib/python3.9/site-packages (from sleeper-py) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/scottenriquez/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.28.1->sleeper-py) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/scottenriquez/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.28.1->sleeper-py) (3.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/scottenriquez/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.28.1->sleeper-py) (2021.10.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/scottenriquez/opt/anaconda3/lib/python3.9/site-packages (from requests>=2.28.1->sleeper-py) (1.26.7)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# 2020 ID: 541384381865115648
# 2021 ID: 706690303247065088
# 2022 ID: 784536701455429632
# 2023 ID: 961113588070985728
# 2024 ID: 1106836321148178432

import pandas as pd
from sleeperpy import *

league_id = '541384381865115648'
rosters = pd.DataFrame(Leagues.get_rosters(league_id))
print(rosters)

   co_owners       keepers           league_id  \
0       None  [4137, 4881]  541384381865115648
1       None          None  541384381865115648
2       None  [3242, 4029]  541384381865115648
3       None          None  541384381865115648
4       None        [5012]  541384381865115648
5       None        [4988]  541384381865115648
6       None        [4217]  541384381865115648
7       None        [1992]  541384381865115648
8       None  [4046, 4951]  541384381865115648
9       None  [4037, 5927]  541384381865115648
10      None        [4131]  541384381865115648
11      None  [4199, 4663]  541384381865115648

                                             metadata            owner_id  \
0                         {'record': 'LWWLWWWWWLWWW'}  463128802726244352
1                         {'record': 'LLLLLWWWLLWLL'}  586272662465060864
2   {'p_nick_3164': 'Daddy', 'record': 'WWWWLLWWWW...   86916165133549568
3                         {'record': 'LLLLWWLWLWWLW'}  602974973434343424
4                         {'record': 'WLWLWLWLWWLWL'}  601103930037944320
5                         {'record': 'WWWLWLLLLWWLL'}  429325714165080064
6                         {'record': 'LLLWLWLLLWLLW'}  586035702630752256
7                         {'record': 'WLLWWLLWWWWWW'}  600100762684563456
8   {'p_nick_232': 'What year is it?', 'record': '...  541051698865418240
9   {'allow_pn_scoring': 'off', 'p_nick_421': '', ...  586300618197475328
10  {'p_nick_947': 'Dumb Julio', 'record': 'LWLWLW...  541054017910829056
11  {'allow_pn_scoring': 'off', 'record': 'LWWLWWL...  540275269586792448

   player_map                                            players reserve  \
0        None  [2238, 3895, 4068, 4137, 4881, 5022, 5038, 585...    None
1        None  [1500, 2197, 2315, 2325, 2410, 3200, 4017, 404...    None
2        None  [2374, 3202, 3242, 4029, 4984, 5007, 538, 5844...    None
3        None  [1476, 167, 1793, 1817, 1848, 2216, 2505, 3664...    None
4        None  [1352, 1426, 2431, 3321, 3423, 3594, 5012, 505...    None
5        None  [1689, 2118, 2331, 3164, 4082, 4988, 4994, 594...    None
6        None  [1049, 2449, 367, 3969, 4036, 4217, 5890, 5916...    None
7        None  [1408, 1992, 2391, 2749, 4035, 4039, 4351, 499...    None
8        None  [2251, 2309, 2320, 3157, 4034, 4046, 4098, 414...    None
9        None  [1144, 3198, 3214, 331, 4037, 4273, 4981, 5248...    None
10       None  [1067, 1234, 1825, 1833, 4066, 4131, 4962, 498...    None
11       None  [1110, 1386, 1466, 2133, 3225, 3976, 4150, 419...    None

    roster_id                                           settings  \
0           1  {'division': 1, 'fpts': 1240, 'fpts_against': ...
1           2  {'division': 1, 'fpts': 1073, 'fpts_against': ...
2           3  {'division': 1, 'fpts': 1359, 'fpts_against': ...
3           4  {'division': 1, 'fpts': 1153, 'fpts_against': ...
4           5  {'division': 1, 'fpts': 1245, 'fpts_against': ...
5           6  {'division': 1, 'fpts': 1165, 'fpts_against': ...
6           7  {'fpts': 1122, 'fpts_against': 1218, 'fpts_aga...
7           8  {'division': 1, 'fpts': 1207, 'fpts_against': ...
8           9  {'division': 1, 'fpts': 1215, 'fpts_against': ...
9          10  {'division': 1, 'fpts': 1157, 'fpts_against': ...
10         11  {'division': 1, 'fpts': 1104, 'fpts_against': ...
11         12  {'division': 1, 'fpts': 1323, 'fpts_against': ...

                                             starters  taxi
0   [4881, 6156, 6813, 6063, 6803, 5022, 4068, 585...  None
1   [4017, 2315, 5850, 4040, 2325, 4602, 2410, 219...  None
2   [4984, 4029, 6790, 538, 5937, 5844, 3242, 6151...  None
3   [5849, 1476, 1848, 2216, 5846, 2505, 5284, 366...  None
4   [954, 2431, 6945, 1426, 3321, 5012, 3423, 1352...  None
5   [6797, 4988, 5967, 1689, 4082, 2118, 6806, 316...  None
6   [1049, 3969, 5916, 2449, 6794, 4217, 5890, 403...  None
7   [96, 4035, 1408, 4039, 1992, 5857, 2391, 5848,...  None
8   [4046, 4098, 2320, 4951, 2309, 2251, 6798, 694...  None
9   [331, 3198, 5892, 4981, 1144, 3214, 4273, 5927...  None
10  [1234, 6845, 5004, 1067, 6886, 4066, 7090, 498...  None
11  [3976, 4663, 4199, 2133, 1110, 1466, 4150, 138...  None

In [3]:
rosters.shape

(12, 12)

In [4]:
matchups = pd.DataFrame(Leagues.get_matchups(league_id, 1))

In [5]:
matchups

,points,players,roster_id,custom_points,matchup_id,starters,starters_points,players_points
0,56.67,"[1479, 3199, 4068, 4137, 4881, 4993, 5068, 585...",1,None,6,"[4881, 5068, 6813, 3199, 1479, 4993, 4137, 585...","[26.5, 1.4, 8.9, 1.7, 3.7, 3.0, 1.7, 3.9, 5.87]","{'1479': 3.7, '3199': 1.7, '4068': 6.9, '4137'..."
1,115.15,"[1339, 147, 2197, 2257, 2315, 3200, 4017, 4040...",2,None,5,"[4017, 5850, 5170, 4040, 2197, 1339, 147, 2315...","[20.82, 31.9, 3.5, 18.9, 2.0, 7.8, 4.6, 11.7, ...","{'1339': 7.8, '147': 4.6, '2197': 2.0, '2257':..."
2,100.46,"[2319, 2374, 2382, 2410, 3242, 344, 4029, 4984...",3,None,4,"[4984, 3242, 4029, 2374, 2319, 5844, 5937, 344...","[28.18, 12.5, 20.8, 9.2, 4.7, 11.6, 3.7, 8.0, ...","{'2319': 4.7, '2374': 9.2, '2382': 1.4, '2410'..."
3,81.06,"[1110, 1408, 1476, 167, 1817, 2216, 2505, 4866...",4,None,3,"[167, 4866, 1408, 4950, 5846, 2505, 1110, 1817...","[19.46, 6.6, 4.6, 0.0, 15.5, 4.5, 5.3, 14.5, 1...","{'1110': 5.3, '1408': 4.6, '1476': 4.8, '167':..."
4,107.52,"[1352, 1426, 24, 3321, 3423, 4455, 5000, 5012,...",5,None,3,"[24, 6130, 5052, 3321, 1426, 5012, 1352, 515, NE]","[23.9, 5.3, 8.2, 10.6, 15.1, 17.8, 11.9, 1.1, ...","{'1352': 11.9, '1426': 15.1, '24': 23.9, '3321..."
5,98.31,"[1502, 1689, 3164, 3294, 4039, 4973, 4988, 554...",6,None,6,"[3294, 4988, 3164, 1689, 4039, 4973, 6786, 587...","[17.64, 4.6, 24.7, 25.0, 4.0, 3.8, 5.9, 1.9, 1...","{'1502': 0.6, '1689': 25.0, '3164': 24.7, '329..."
6,82.50,"[1825, 184, 2449, 2588, 289, 3198, 3969, 4217,...",7,None,1,"[289, 3198, 956, 2449, 6789, 4217, 1825, 4962,...","[14.4, 13.1, 2.9, 8.6, 6.6, 5.3, 6.1, 9.7, 15.8]","{'1825': 6.1, '184': 11.4, '2449': 8.6, '2588'..."
7,127.59,"[1992, 2378, 2391, 2749, 3271, 3306, 4035, 500...",8,None,5,"[96, 2391, 4035, 5848, 1992, 3271, 3306, 2749,...","[30.76, 16.9, 18.7, 10.1, 7.3, 4.0, 6.7, 21.1,...","{'1992': 7.3, '2378': 2.4, '2391': 16.9, '2749..."
8,99.76,"[2161, 2309, 232, 2320, 3157, 3202, 4034, 4046...",9,None,1,"[4046, 4034, 4098, 3157, 4951, 3202, 2309, 232...","[20.44, 25.5, 7.1, 11.2, 8.5, 1.5, 8.1, 12.6, ...","{'2161': 10.4, '2309': 8.1, '232': 2.4, '2320'..."
9,111.38,"[3214, 4037, 4157, 421, 4273, 4981, 5122, 5872...",10,None,2,"[421, 6820, 4273, 4037, 5927, 3214, 4981, 5892...","[16.18, 19.8, 18.6, 7.9, 6.1, 7.3, 24.9, 7.4, ...","{'3214': 7.3, '4037': 7.9, '4157': 4.7, '421':..."
10,79.38,"[1234, 2078, 2238, 4018, 4066, 4131, 4152, 498...",11,None,4,"[1234, 4018, 4152, 947, 4983, 4066, 6845, 2078...","[30.78, 5.1, 5.6, 15.7, 5.4, 0.9, 8.7, 2.2, 5.0]","{'1234': 30.78, '2078': 2.2, '2238': 13.0, '40..."
11,91.38,"[1067, 1466, 1848, 2133, 2168, 3161, 3225, 367...",12,None,2,"[3161, 4199, 4663, 2133, 1067, 1466, 5038, 693...","[12.0, 12.6, 8.7, 27.6, 5.5, 11.0, 5.0, 4.3, 4...","{'1067': 5.5, '1466': 11.0, '1848': 5.2, '2133..."

In [6]:
week_zero = pd.merge(rosters, matchups, on='roster_id', how='inner')

In [7]:
week_zero

,co_owners,keepers,league_id,metadata,owner_id,player_map,players_x,reserve,roster_id,settings,starters_x,taxi,points,players_y,custom_points,matchup_id,starters_y,starters_points,players_points
0,None,"[4137, 4881]",541384381865115648,{'record': 'LWWLWWWWWLWWW'},463128802726244352,None,"[2238, 3895, 4068, 4137, 4881, 5022, 5038, 585...",None,1,"{'division': 1, 'fpts': 1240, 'fpts_against': ...","[4881, 6156, 6813, 6063, 6803, 5022, 4068, 585...",None,56.67,"[1479, 3199, 4068, 4137, 4881, 4993, 5068, 585...",None,6,"[4881, 5068, 6813, 3199, 1479, 4993, 4137, 585...","[26.5, 1.4, 8.9, 1.7, 3.7, 3.0, 1.7, 3.9, 5.87]","{'1479': 3.7, '3199': 1.7, '4068': 6.9, '4137'..."
1,None,None,541384381865115648,{'record': 'LLLLLWWWLLWLL'},586272662465060864,None,"[1500, 2197, 2315, 2325, 2410, 3200, 4017, 404...",None,2,"{'division': 1, 'fpts': 1073, 'fpts_against': ...","[4017, 2315, 5850, 4040, 2325, 4602, 2410, 219...",None,115.15,"[1339, 147, 2197, 2257, 2315, 3200, 4017, 4040...",None,5,"[4017, 5850, 5170, 4040, 2197, 1339, 147, 2315...","[20.82, 31.9, 3.5, 18.9, 2.0, 7.8, 4.6, 11.7, ...","{'1339': 7.8, '147': 4.6, '2197': 2.0, '2257':..."
2,None,"[3242, 4029]",541384381865115648,"{'p_nick_3164': 'Daddy', 'record': 'WWWWLLWWWW...",86916165133549568,None,"[2374, 3202, 3242, 4029, 4984, 5007, 538, 5844...",None,3,"{'division': 1, 'fpts': 1359, 'fpts_against': ...","[4984, 4029, 6790, 538, 5937, 5844, 3242, 6151...",None,100.46,"[2319, 2374, 2382, 2410, 3242, 344, 4029, 4984...",None,4,"[4984, 3242, 4029, 2374, 2319, 5844, 5937, 344...","[28.18, 12.5, 20.8, 9.2, 4.7, 11.6, 3.7, 8.0, ...","{'2319': 4.7, '2374': 9.2, '2382': 1.4, '2410'..."
3,None,None,541384381865115648,{'record': 'LLLLWWLWLWWLW'},602974973434343424,None,"[1476, 167, 1793, 1817, 1848, 2216, 2505, 3664...",None,4,"{'division': 1, 'fpts': 1153, 'fpts_against': ...","[5849, 1476, 1848, 2216, 5846, 2505, 5284, 366...",None,81.06,"[1110, 1408, 1476, 167, 1817, 2216, 2505, 4866...",None,3,"[167, 4866, 1408, 4950, 5846, 2505, 1110, 1817...","[19.46, 6.6, 4.6, 0.0, 15.5, 4.5, 5.3, 14.5, 1...","{'1110': 5.3, '1408': 4.6, '1476': 4.8, '167':..."
4,None,[5012],541384381865115648,{'record': 'WLWLWLWLWWLWL'},601103930037944320,None,"[1352, 1426, 2431, 3321, 3423, 3594, 5012, 505...",None,5,"{'division': 1, 'fpts': 1245, 'fpts_against': ...","[954, 2431, 6945, 1426, 3321, 5012, 3423, 1352...",None,107.52,"[1352, 1426, 24, 3321, 3423, 4455, 5000, 5012,...",None,3,"[24, 6130, 5052, 3321, 1426, 5012, 1352, 515, NE]","[23.9, 5.3, 8.2, 10.6, 15.1, 17.8, 11.9, 1.1, ...","{'1352': 11.9, '1426': 15.1, '24': 23.9, '3321..."
5,None,[4988],541384381865115648,{'record': 'WWWLWLLLLWWLL'},429325714165080064,None,"[1689, 2118, 2331, 3164, 4082, 4988, 4994, 594...",None,6,"{'division': 1, 'fpts': 1165, 'fpts_against': ...","[6797, 4988, 5967, 1689, 4082, 2118, 6806, 316...",None,98.31,"[1502, 1689, 3164, 3294, 4039, 4973, 4988, 554...",None,6,"[3294, 4988, 3164, 1689, 4039, 4973, 6786, 587...","[17.64, 4.6, 24.7, 25.0, 4.0, 3.8, 5.9, 1.9, 1...","{'1502': 0.6, '1689': 25.0, '3164': 24.7, '329..."
6,None,[4217],541384381865115648,{'record': 'LLLWLWLLLWLLW'},586035702630752256,None,"[1049, 2449, 367, 3969, 4036, 4217, 5890, 5916...",None,7,"{'fpts': 1122, 'fpts_against': 1218, 'fpts_aga...","[1049, 3969, 5916, 2449, 6794, 4217, 5890, 403...",None,82.50,"[1825, 184, 2449, 2588, 289, 3198, 3969, 4217,...",None,1,"[289, 3198, 956, 2449, 6789, 4217, 1825, 4962,...","[14.4, 13.1, 2.9, 8.6, 6.6, 5.3, 6.1, 9.7, 15.8]","{'1825': 6.1, '184': 11.4, '2449': 8.6, '2588'..."
7,None,[1992],541384381865115648,{'record': 'WLLWWLLWWWWWW'},600100762684563456,None,"[1408, 1992, 2391, 2749, 4035, 4039, 4351, 499...",None,8,"{'division': 1, 'fpts': 1207, 'fpts_against': ...","[96, 4035, 1408, 4039, 1992, 5857, 2391, 5848,...",None,127.59,"[1992, 2378, 2391, 2749, 3271, 3306, 4035, 500...",None,5,"[96, 2391, 4035, 5848, 1992, 3271, 3306, 2749,...","[30.76, 16.9, 18.7, 10.1, 7.3, 4.0, 6.7, 21.1,...","{'1992': 7.3, '2378': 2.4, '2391': 16.9, '2749..."
8,None,"[4046, 4951]",541384381865115648,"{'p_nick_232': 'What year is it?', 'record': '...",541051698865418240,None,"[2251, 2309, 2320, 3157, 4034, 4046, 4098, 414...",None,9,"{'division': 1, 'fpts': 1215, 'fpts_against': ...","[4046, 4098, 2320, 4951, 2309, 2251, 6798, 694...",None,99.76,"[2161, 2309, 232, 2320, 3157, 3202, 4034, 4046...",None,1,"[4046, 4034, 4098, 3157, 4951, 3202, 2309, 232...","[20.44, 25.5, 7.1, 11.2, 8.5, 1.5, 8.1, 12.6, ...","{'2161': 10.4, '2309': 8.1, '232': 2.4, '2320'..."
9,None,"[4037, 5927]",541384381865115648,"{'allow_pn_scoring': 'off', 'p_nick_421': '', ...",586300618197475328,None,"[1144, 3198, 3214, 331, 4037, 4273, 4981, 5248...",None,10,"{'division': 1, 'fpts': 1157, 'fpts_against': ...","[331, 3198, 5892, 4981, 1144, 3214, 4273, 5927...",None,111.38,"[3214, 4037, 4157, 421, 4273, 4981, 5122, 5872...",None,2,"[421, 6820, 4273, 4037, 5927, 3214, 4981, 5892...","[16.18, 19.8, 18.6, 7.9, 6.1, 7.3, 24.9, 7.4, ...","{'3214': 7.3, '4037': 7.9, '4157': 4.7, '421':..."
10,None,[4131],541384381865115648,"{'p_nick_947': 'Dumb Julio', 'record': 'LWLWLW...",541054017910829056,None,"[1067, 1234, 1825, 1833, 4066, 4131, 4962, 498...",None,11,"{'division': 1, 'fpts': 1104, 'fpts_against': ...","[1234, 6845, 5004, 1067, 6886, 4066, 7090, 498...",None,79.38,"[1234, 2078, 2238, 4018, 4066, 4131, 4152, 498...",None,4,"[1234, 4018, 4152, 947, 4983, 4066, 6845, 2078...","[30.78, 5.1, 5.6, 15.7, 5.4, 0.9, 8.7, 2.2, 5.0]","{'1234': 30.78, '2078': 2.2, '2238': 13.0, '40..."
11,None,"[4199, 4663]",541384381865115648,"{'allow_pn_scoring': 'off', 'record': 'LWWLWWL...",540275269586792448,None,"[1110, 1386, 1466, 2133, 3225, 3976, 4150, 419...",None,12,"{'division': 1, 'fpts': 1323, 'fpts_against': ...","[3976, 4663, 4199, 2133, 1110, 1466, 4150, 138...",None,91.38,"[1067, 1466, 1848, 2133, 2168, 3161, 3225, 367...",None,2,"[3161, 4199, 4663, 2133, 1067, 1466, 5038, 693...","[12.0, 12.6, 8.7, 27.6, 5.5, 11.0, 5.0, 4.3, 4...","{'1067': 5.5, '1466': 11.0, '1848': 5.2, '2133..."

In [8]:
nfl_player_data = pd.read_parquet('s3://datalakestack-datalakebucket0256ea8e-jlou2zsfqxmr/sleeper/nfl-player-data/player-data.parquet')

In [9]:
nfl_player_data.columns

Index(['first_name', 'gsis_id', 'age', 'team_abbr', 'depth_chart_order',
       'high_school', 'birth_country', 'active', 'college', 'news_updated',
       'birth_date', 'birth_city', 'sport', 'weight', 'practice_description',
       'full_name', 'competitions', 'years_exp', 'injury_body_part',
       'rotoworld_id', 'status', 'number', 'search_first_name',
       'search_last_name', 'espn_id', 'hashtag', 'metadata', 'birth_state',
       'player_id', 'team', 'oddsjam_id', 'height', 'opta_id', 'swish_id',
       'last_name', 'search_rank', 'search_full_name', 'rotowire_id',
       'fantasy_positions', 'injury_status', 'stats_id',
       'depth_chart_position', 'sportradar_id', 'pandascore_id', 'position',
       'yahoo_id', 'injury_start_date', 'practice_participation',
       'fantasy_data_id', 'injury_notes'],
      dtype='object')

In [ ]:
week_zero['keepers_with_player_names'] = week_zero['keepers']